/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpustakaan;

import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alifia
 */
public class FormPeminjaman extends javax.swing.JFrame {

    /**
     * Creates new form FormPeminjaman
     */
    public FormPeminjaman() {
        initComponents();
    }

    public void tampilkan() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Input_lama = new javax.swing.JTextField();
        btnPinjam = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_pencarian = new javax.swing.JTable();
        btnCari1 = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_buku = new javax.swing.JTable();
        btnKonfirmasi = new javax.swing.JButton();
        LamaPinjam = new javax.swing.JLabel();
        JudulBuku = new javax.swing.JLabel();
        Input_cari1 = new javax.swing.JTextField();

             
        btnCari1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCari1MouseClicked(evt);
            }
        });
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });
        btnKonfirmasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKonfirmasiMouseClicked(evt);
            }
        });
        btnPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPinjamMouseClicked(evt);
            }
        });

        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel1.setBackground(new java.awt.Color(222, 222, 222));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setText("Peminjaman Buku");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Input_lama.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        btnPinjam.setBackground(new java.awt.Color(222, 222, 222));
        btnPinjam.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnPinjam.setText("Pinjam");

        Table_pencarian.setForeground(new java.awt.Color(222, 222, 222));
        Table_pencarian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Judul"
            }
        ));
        Table_pencarian.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(Table_pencarian);

        btnCari1.setBackground(new java.awt.Color(222, 222, 222));
        btnCari1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnCari1.setText("Cari");

        btnBatal.setBackground(new java.awt.Color(222, 222, 222));
        btnBatal.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnBatal.setText("Batal");

        Table_buku.setForeground(new java.awt.Color(222, 222, 222));
        Table_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Judul"
            }
        ));
        Table_buku.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(Table_buku);

        btnKonfirmasi.setBackground(new java.awt.Color(222, 222, 222));
        btnKonfirmasi.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnKonfirmasi.setText("Konfirmasi");

        LamaPinjam.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        LamaPinjam.setText("Lama ");

        JudulBuku.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        JudulBuku.setText("Judul Buku");

        Input_cari1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Input_cari1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCari1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LamaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Input_lama, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 89, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKonfirmasi)
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JudulBuku))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LamaPinjam)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Input_cari1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Input_lama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnCari1MouseClicked(java.awt.event.MouseEvent evt) {
        String judul = Input_cari1.getText();
        Perpustakaan.controllerPeminjaman.cariBuku(judul);
    }

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {
        DefaultTableModel model = (DefaultTableModel) Table_buku.getModel();
        int selectedRow = Table_buku.getSelectedRow();
        if (selectedRow != -1) { // pastikan ada baris yang dipilih
            BukuProvider dataProvider = new BukuProvider();
            String judul = (String) model.getValueAt(selectedRow, 0);
            Buku buku = dataProvider.selectBuku(judul).get(0);
            hapusBuku(buku);
        }
        ArrayList<Buku> list = new ArrayList<>();
        list.addAll(bukuDipinjamCollection);
        tampilPinjaman(list);
    }

    private void btnKonfirmasiMouseClicked(java.awt.event.MouseEvent evt) { 
        Perpustakaan.controllerPeminjaman.pinjam(bukuDipinjamCollection);
    }

    private void btnPinjamMouseClicked(java.awt.event.MouseEvent evt) {
        DefaultTableModel model = (DefaultTableModel) Table_pencarian.getModel();
        int selectedRow = Table_pencarian.getSelectedRow();
        if (selectedRow != -1) { // pastikan ada baris yang dipilih
            BukuProvider dataProvider = new BukuProvider();
            String judul = (String) model.getValueAt(selectedRow, 0);
            Buku buku = dataProvider.selectBuku(judul).get(0);
            String lama = Input_lama.getText();
            System.out.print(lama);
            try {
                if(Integer.parseInt(lama) < 0) {
                    DialogUI dialogUI = new DialogUI("Isi lama peminjaman!");
                    dialogUI.pack();
                    dialogUI.setLocationRelativeTo(null);
                    dialogUI.setVisible(true); return;
                } else {
                    tambahBuku(buku, Integer.parseInt(lama));
                }
            } catch (NumberFormatException e) {
                DialogUI dialogUI = new DialogUI("Isi lama peminjaman!");
                dialogUI.pack();
                dialogUI.setLocationRelativeTo(null);
                dialogUI.setVisible(true); return;
            }
            
            ArrayList<Buku> list = new ArrayList<>();
            list.addAll(bukuDipinjamCollection);
            tampilPinjaman(list);
        }
        else {
            DialogUI dialogUI = new DialogUI("Pilih buku!");
            dialogUI.pack();
            dialogUI.setLocationRelativeTo(null);
            dialogUI.setVisible(true);
        }
    }

    private void tambahBuku(Buku buku, int lama) {
        BukuDipinjam bukuDipinjam = new BukuDipinjam(buku.judul,lama);
        bukuDipinjamCollection.add(bukuDipinjam);
    }

    private void tampilPinjaman(ArrayList<Buku> bukuCollection) {
        Object[] kolom = { "Judul" };
        DefaultTableModel model = new DefaultTableModel(kolom, 0);
        
        for(Buku buku : bukuCollection) {
            Object[] baris = { buku.judul };
            model.addRow(baris);
        }
        
        Table_buku.setModel(model);
    }

    private void hapusBuku(Buku buku) {
        for (Buku bukuDipinjam : bukuDipinjamCollection) {
            if(bukuDipinjam.judul.equals(buku.judul)) {
                bukuDipinjamCollection.remove(bukuDipinjam);
                break;
            }
        }
    }

    public void display(ArrayList<Buku> bukuList) {
        Object[] kolom = { "Judul" };
        DefaultTableModel model = new DefaultTableModel(kolom, 0);
        
        for(Buku buku : bukuList) {
            Object[] baris = { buku.judul };
            model.addRow(baris);
        }
        
        Table_pencarian.setModel(model);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField Input_cari1;
    private javax.swing.JTextField Input_lama;
    private javax.swing.JLabel JudulBuku;
    private javax.swing.JLabel LamaPinjam;
    private javax.swing.JTable Table_buku;
    private javax.swing.JTable Table_pencarian;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari1;
    private javax.swing.JButton btnKonfirmasi;
    private javax.swing.JButton btnPinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private ArrayList<BukuDipinjam> bukuDipinjamCollection = new ArrayList<BukuDipinjam>();
    // End of variables declaration                   
}
